# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


      app.exception_controller:
          class: AppBundle\Controller\CustomExceptionController
          arguments: ['@twig', '%kernel.debug%']

      app.services.commonservices:
          class: AppBundle\Services\CommonService
          arguments: ["@doctrine.orm.entity_manager","@session","@security.authorization_checker"]

      app.twig.twigfunctions:
          class: AppBundle\Twig\TwigFunctions
          public: false
          tags:
              - { name: twig.extension }

