#Default Controller

homepage:
  path: /
  defaults: {_controller: AppBundle:Default:index}

products:
  path: /products/{serviceId}
  defaults: {_controller: AppBundle:Default:getProducts, serviceId: 0}
  requirements:
        serviceId: '^\d+$'

productById:
  path: /product/{productId}
  defaults: {_controller: AppBundle:Default:getProductById}
  requirements:
          productId: '^\d+$'

#SecurityController

login:
  path: /login
  defaults:  {_controller: AppBundle:Security:login}

logout:
  path: /logout
  defaults: {_controller: AppBundle:Security:logout}
