AppBundle\Entity\Categories:
    type: entity
    table: categories

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        category:
            type: string
            nullable: false
            length: 255
            options:
                unsigned: false
            column: category
        visible:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: visible

    oneToMany:
            services:
                targetEntity: Services
                mappedBy: categories

    lifecycleCallbacks: {  }
