AppBundle\Entity\Products:
    type: entity
    table: products

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        serviceId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: service_id
        productName:
            type: string
            nullable: false
            length: 255
            options:
                unsigned: false
            column: product_name
        visible:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: visible

    manyToOne:
            services:
                targetEntity: Services
                cascade: {  }
                fetch: LAZY
                mappedBy: null
                inversedBy: null
                joinColumns:
                    service_id:
                        referencedColumnName: id
                orphanRemoval: false

    lifecycleCallbacks: {  }
