AppBundle\Entity\Products:
    type: entity
    table: products

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:

        productName:
            type: string
            nullable: false
            length: 255
            options:
                unsigned: false
            column: product_name
        visible:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: visible
        slug:
            type: string
            nullable: false
            options:
                unsigned: false
            column: slug

    manyToMany:
            services:
              targetEntity: Services
              mappedBy: products

    lifecycleCallbacks: {  }
