AppBundle\Entity\Services:
    type: entity
    table: services

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: category_id
        serviceName:
            type: string
            nullable: false
            length: 255
            options:
                unsigned: false
            column: service_name
        visible:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: visible

    manyToOne:
            categories:
                targetEntity: Categories
                cascade: {  }
                fetch: LAZY
                mappedBy: null
                inversedBy: null
                joinColumns:
                    category_id:
                        referencedColumnName: id
                orphanRemoval: false

    manyToMany:
            products:
              targetEntity: Products
              inversedBy: services
              joinTable:
                name: serviceProductRelation
                joinColumns:
                  serviceId:
                    referencedColumnName: id
                inverseJoinColumns:
                  productId:
                    referencedColumnName: id


    lifecycleCallbacks: {  }
